/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _testing;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void assertingTrueStuff() {
        assertTrue(true);
    }

    // uncomment to ensure this test fails when you run your tests
//    @Test
//    public void thisTestShouldFail() {
//        assertTrue(false);
//    }
}
