CREATE TABLE IF NOT EXISTS PROPERTIES
(
  id INT NOT NULL,
  ADDRESS_LINE_1 VARCHAR(200) NOT NULL,
  ADDRESS_LINE_2 VARCHAR(35),
  ZIP_CODE INT,
  SQ_FOOTAGE INT,
  LOT_SIZE INT,
  ASKING_PRICE BIGINT NOT NULL
);

